Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
list_=['1','2','3','4','5'];

In [2]:
import numpy as np

In [4]:
array_list=np.array(object=list_)

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

Yes there is a difference between list and array . List is in-built data structure. while array is a imported 
one as we need to import it from numpy.
List can contain different data types. but array cant contain different data types.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [13]:
for i in list_:
    print(i+" data type= ",type(i));

1 data type=  <class 'str'>
2 data type=  <class 'str'>
3 data type=  <class 'str'>
4 data type=  <class 'str'>
5 data type=  <class 'str'>


In [14]:
for i in array_list:
    print(i+" data type= ",type(i));

1 data type=  <class 'numpy.str_'>
2 data type=  <class 'numpy.str_'>
3 data type=  <class 'numpy.str_'>
4 data type=  <class 'numpy.str_'>
5 data type=  <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [15]:
array_list = np.array(object = list_, dtype = int)

In [16]:
array_list

array([1, 2, 3, 4, 5])

In [21]:
for i in array_list:
    print(i," data type= ",type(i));

1  data type=  <class 'numpy.int64'>
2  data type=  <class 'numpy.int64'>
3  data type=  <class 'numpy.int64'>
4  data type=  <class 'numpy.int64'>
5  data type=  <class 'numpy.int64'>


The data type of each element in array list is int and in list it is str.

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [23]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [24]:
num_array=np.array(object=num_list)

In [25]:
num_array.shape

(2, 3)

In [26]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [39]:
array_zero=np.zeros([3,3],dtype=int)

In [40]:
array_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [42]:
array_identity=np.identity(5,dtype=int)

In [43]:
array_identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])